name: Build RustyTodos macOS

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Upload macOS binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: RustyTodos-macos
          path: target/release/rustytodos
