name: Build RustyTodos macOS

on:
  push:
    branches:
      - master  # Your branch name (adjust if different)
  pull_request:
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build RustyTodos
        run: cargo build --release

      - name: Upload macOS binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: RustyTodos-macos
          path: target/release/rustytodos

